version: '2'
services:
  server:
    build: .
    ports:
      - "0.0.0.0:25565:25565"
    volumes:
      - "/data/minecraft:/data"
      - "./supervisor/supervisord.conf:/etc/supervisor/supervisord.conf"
      - "./supervisor/conf.d/minecraft.conf:/etc/supervisor/conf.d/minecraft.conf"
      - "./minecraft/ops.txt:/usr/local/etc/minecraft/ops.txt"
      - "./minecraft/white-list.txt:/usr/local/etc/minecraft/white-list.txt"
      - "./minecraft/server.properties:/usr/local/etc/minecraft/server.properties"
      - "./scripts/start:/start"
#    tty: true
#    stdin_open: true
    restart: always
